# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  bookrental.dev.api:
    build:
      context: "C:\\Users\\balib\\source\\repos\\BookRental.Dev"
      dockerfile: "src/External/BookRental.Dev.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/BookRental.Dev.WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bookrentaldevapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\balib\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\balib\\source\\repos\\BookRental.Dev\\src\\External\\BookRental.Dev.WebApi:/app:rw"
    - "C:\\Users\\balib\\source\\repos\\BookRental.Dev:/src:rw"
    working_dir: "/app"
